// <auto-generated />
using System;
using Corona_Statistics.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Corona_Statistics.Migrations
{
    [DbContext(typeof(CoronaStatisticsContext))]
    partial class CoronaStatisticsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("Corona_Statistics.DataAccess.Covid19Case", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Cases")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("Deaths")
                        .HasColumnType("int");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("Population")
                        .HasColumnType("int");

                    b.Property<int>("SevenDayIncidence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId")
                        .IsUnique();

                    b.ToTable("Covid19Cases");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Code")
                        .HasColumnType("int");

                    b.Property<int>("Covid19CasesId")
                        .HasColumnType("int");

                    b.Property<int?>("FederalStateId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("FederalStateId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.FederalState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("FederalStates");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.TotalCase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CasesSum")
                        .HasColumnType("int");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DeathsSum")
                        .HasColumnType("int");

                    b.Property<int>("PopulationsSum")
                        .HasColumnType("int");

                    b.Property<int>("SevenDaysIncidentsSum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TotalCases");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.Covid19Case", b =>
                {
                    b.HasOne("Corona_Statistics.DataAccess.District", "District")
                        .WithOne("Covid19Case")
                        .HasForeignKey("Corona_Statistics.DataAccess.Covid19Case", "DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("District");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.District", b =>
                {
                    b.HasOne("Corona_Statistics.DataAccess.FederalState", "FederalState")
                        .WithMany("Districts")
                        .HasForeignKey("FederalStateId");

                    b.Navigation("FederalState");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.District", b =>
                {
                    b.Navigation("Covid19Case");
                });

            modelBuilder.Entity("Corona_Statistics.DataAccess.FederalState", b =>
                {
                    b.Navigation("Districts");
                });
#pragma warning restore 612, 618
        }
    }
}
